### ISSUE TITLE
Questions on Qwest CBBE/Bodyslide

### ISSUE THREAD

**Issue by Hieronymos2** [Althro/QWEST#2]
First, thank you so much for such an amaaaazing Wabbajack mod-pack! My last manual install of Phoenix Flavor 2 years ago...plus all the quest mods they don't include--but you do--took me a day and a half. And still didn't look half as good as Quest does now! Nor was it as stable. Please excuse my posting this here, as it's not clear where else to do so, as there doesn't appear to be a link to your site's forum(s).

Two issues, though:
1) What BethINI settings for a medium high rig? [RTX2080S 8GB; 32GB RAM; i9 3,7GHz] I know that Qwest advertizes itself as the pack that includes most major DLC-sized quests and is geared for lower-end rigs. I used BethINI to use 'High' preset, and care not for ENB's; but assume there are more effective sub-settings to use with Qwest's specific texture, animation, etc. mods?

2) Body: CBBE Curvy is my preference. Can I just reinstall CBBE without borking any dependencies? 
If I want to change Bodyslide appearance for specific outfits, can it be done without damaging modpack?

Thanks again.

**Comment by chri3i** [comment]
1.) BethINI high is fine for you rig, don't set it to ultra as the difference is way too small for the performance loss. and i'd highly suggest using the ENB present in the list as it makes the game so much prettier. you'll be fine with the 'high end ENB'

2.) we don't support changes to the list as it is so you have to figure that out yourself.
