### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by JrdnChrch** [Althro/QWEST#4]
**Upload your crashlog**

If you've crashed, upload your crashlog from `Tool Cache\NetScriptFramework`. Reports of crashes that do not include a crashlog will be **ignored and closed.**

**Required: Modlist.txt**

I don't have a Modlist.txt, installation hasn't gotten that far. I have the Wabbajack log if that is necessary. 

**Describe the bug**

I'm currently trying to install this modlist for the first time, but as of right now I'm receiving an error. According to the install feed I'm unable to download xLODGen.83.7z. 

I saw that this was one of the links you recommended installing beforehand because it causes issues, but the link says that nothing is there anymore.

"51.25 - Unable to download xLODGen.83.7z (MegaDownloader+State|https://mega.nz/file/EcJhgKpY#4Q86Rd1hUepjm233r8Q_7x3fTWx9axJN2CUc8FXrBsg)
51.25 - Cannot continue, was unable to download one or more archives"

**To Reproduce**

The error happens when I try to install QWEST through the Wabbajack client.

I have tried restarting the download, the Wabbajack client, and my computer several times.

**Expected behavior**

To complete the installation of the modlist.

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug. If your bug is location based, use the book from [Where in Special Edition am I](https://www.nexusmods.com/skyrimspecialedition/mods/30907) mod.

**Modlist version**

3.8

**Did you add any additional mods?**

I haven't touched any other mods. I'm just trying to install the modlist provided on the Wabbajack client.

***YOU MUST DECLARE IF YOU HAVE MODIFIED THE LIST.***

**Comment by TheSpaniard** [comment]
Join the Wabbajack discord server, navigate to the Qwest support channel and grab said file from the pins in the referenced channel. Follow the instructions on the pin you get the file from.

Discord link:
https://discord.gg/wabbajack

**Comment by JrdnChrch** [comment]
Thank you! That fixed my issue.
